dbt_transform:
  outputs:
    dev:
      dataset: ticketsim_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ~/.google/credentials/key.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: elite-bird-367213
      threads: 4
      type: bigquery
  target: dev
